In [14]:
import pandas as pd
import numpy as np

In [3]:
unmatched = pd.read_csv('/media/johnattan/LaCie/Twitter_Terms/ALCOHOL/2020-6.csv')
matched = pd.read_csv('/media/johnattan/LaCie/Twitter_Terms/ALCOHOL/GEO-Tweets.csv')

In [4]:
unmatched.head()

,Unnamed: 0,id,text,created_at,urls,profile_location,geotag_location,geotag_country
0,0,1267244471277760513,As the country looks to bounce back from the p...,2020-06-01 00:00:00+00:00,['https://twitter.com/i/web/status/12672444712...,"Baltimore, MD",NaN,NaN
1,1,1267244894915002373,üè≠ We‚Äôve diverted resources to make isopropyl a...,2020-06-01 00:01:41+00:00,['https://twitter.com/i/web/status/12638328504...,‡¥ï‡µá‡¥∞‡¥≥‡¥Ç,NaN,NaN
2,2,1267244929320919041,As the country looks to bounce back from the p...,2020-06-01 00:01:50+00:00,['https://twitter.com/i/web/status/12672444712...,Maryland,NaN,NaN
3,3,1267245217821982720,Coronavirus cases is near 2 million in the US ...,2020-06-01 00:02:58+00:00,['https://twitter.com/i/web/status/12672428215...,ùôñùôûùôßùô•ùô°ùôñùô£ùôö,NaN,NaN
4,4,1267245262210244608,Coronavirus cases is near 2 million in the US ...,2020-06-01 00:03:09+00:00,['https://twitter.com/i/web/status/12672428215...,bffies :P ||,NaN,NaN

In [5]:
matched.head()

,Unnamed: 0,Unnamed: 0.1,id,text,created_at,state
0,0,0,1.215713e+18,"Jan. 10 news: Alcohol deaths double, new coron...",2020-01-10 19:11:32+00:00,NY
1,1,1,1.217161e+18,Jan. 14 News: Air in Australia posed a threat ...,2020-01-14 19:06:03+00:00,NY
2,2,3,1.217169e+18,How to handwash? Use üßº and water for at least ...,2020-01-14 19:38:09+00:00,NJ
3,3,9,1.217170e+18,How to handwash? Use üßº and water for at least ...,2020-01-14 19:40:43+00:00,NY
4,4,15,1.217170e+18,How to handwash? Use üßº and water for at least ...,2020-01-14 19:42:09+00:00,NY

In [30]:
unmatched.index[unmatched.created_at == '2020-06-01 00:00:00+00:00']

[0]

In [27]:
matched.iloc[1121].values

array([1121, 0, 1.2672444712777605e+18,
       'As the country looks to bounce back from the pandemic, some state leaders say more permanent alcohol-on-demand laws could be the fuel that the restaurant and service industry needs to restart their economies. https://t.co/2FbP06AQ0E',
       '2020-06-01 00:00:00+00:00', 'MD'], dtype=object)

# OK we have the indexes where both meet at June 1st, 2020, now we'll check 100 of em

In [59]:
base = 1121 + 20
matched.iloc[base:(base + 10)].head(50)

,Unnamed: 0,Unnamed: 0.1,id,text,created_at,state
1141,1141,149,1.267308e+18,The latest Daily Sanitizer News! https://t.co/...,2020-06-01 04:11:01+00:00,CA
1142,1142,179,1.267318e+18,DEMOCRATS LAST WEEK: It‚Äôs ok if you die from s...,2020-06-01 04:52:57+00:00,CA
1143,1143,185,1.267319e+18,DEMOCRATS LAST WEEK: It‚Äôs ok if you die from s...,2020-06-01 04:55:32+00:00,PA
1144,1144,186,1.267319e+18,DEMOCRATS LAST WEEK: It‚Äôs ok if you die from s...,2020-06-01 04:55:37+00:00,MI
1145,1145,188,1.267319e+18,DEMOCRATS LAST WEEK: It‚Äôs ok if you die from s...,2020-06-01 04:56:04+00:00,PA
1146,1146,190,1.267319e+18,DEMOCRATS LAST WEEK: It‚Äôs ok if you die from s...,2020-06-01 04:57:23+00:00,CA
1147,1147,194,1.267320e+18,DEMOCRATS LAST WEEK: It‚Äôs ok if you die from s...,2020-06-01 05:00:04+00:00,TX
1148,1148,201,1.267320e+18,DEMOCRATS LAST WEEK: It‚Äôs ok if you die from s...,2020-06-01 05:01:27+00:00,CA
1149,1149,202,1.267320e+18,DEMOCRATS LAST WEEK: It‚Äôs ok if you die from s...,2020-06-01 05:01:56+00:00,AL
1150,1150,206,1.267321e+18,DEMOCRATS LAST WEEK: It‚Äôs ok if you die from s...,2020-06-01 05:03:24+00:00,CA

In [6]:
base = 2000
unmatched.iloc[base:(base + 10)].head(50)

,Unnamed: 0,id,text,created_at,urls,profile_location,geotag_location,geotag_country
2000,2000,1267464061949808643,After a hard night of domestic terrorism - I h...,2020-06-01 14:32:35+00:00,['https://twitter.com/i/web/status/12674391963...,"Virginia, USA",NaN,NaN
2001,2001,1267464072225787906,CIC @Julius_S_Malema highlights the dangers of...,2020-06-01 14:32:37+00:00,['https://twitter.com/i/web/status/12673887587...,South Africa,NaN,NaN
2002,2002,1267464201255243778,Women with #Covid19 can breastfeed ü§± They shou...,2020-06-01 14:33:08+00:00,['https://twitter.com/i/web/status/12674642012...,"Lagos, Nigeria",NaN,NaN
2003,2003,1267464273837555718,#CoronaIsNotAJoke To protect yourself and othe...,2020-06-01 14:33:25+00:00,['https://twitter.com/i/web/status/12674642738...,i live in my own World,NaN,NaN
2004,2004,1267464376728125442,BBC News - Coronavirus: South Africans cheer a...,2020-06-01 14:33:50+00:00,['https://www.bbc.com/news/world-africa-528747...,"London, England",NaN,NaN
2005,2005,1267464423557550082,@mellowmilez @EFFSouthAfrica @Julius_S_Malema ...,2020-06-01 14:34:01+00:00,NaN,Zimbabwe,NaN,NaN
2006,2006,1267464450665320450,#CoronaIsNotAJoke Hand sanitizers recommended ...,2020-06-01 14:34:08+00:00,['https://twitter.com/i/web/status/12674644506...,i live in my own World,NaN,NaN
2007,2007,1267464854258024448,#CoronaIsNotAJoke Hand sanitizers recommended ...,2020-06-01 14:35:44+00:00,['https://twitter.com/i/web/status/12674644506...,"Punjab, Pakistan",NaN,NaN
2008,2008,1267464905478885385,Are you trying to cope with #COVID19 by using ...,2020-06-01 14:35:56+00:00,['https://twitter.com/i/web/status/12674649054...,Central Texas Counties,NaN,NaN
2009,2009,1267464906066071553,#CoronaIsNotAJoke To protect yourself and othe...,2020-06-01 14:35:56+00:00,['https://twitter.com/i/web/status/12674642738...,"Punjab, Pakistan",NaN,NaN

|             | Pred Yes    | Pred No     |
| ----------- | ----------- | ----------- |
| Actual No   | 0           | 75          |
| Actual Yes  | 23          | 2           |

In [15]:

time_vec = unmatched.created_at.values
#time_vec[2000][11:13]

def strip_time(x):
    return x[11:13]

np.vectorize(strip_time)(time_vec)

array(['00', '00', '00', ..., '23', '23', '23'], dtype='<U2')

In order to save time for complex US search over larger datasets, Tweets will be sliced between 3 PM and 10 PM